import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col " suppressHydrationWarning>
        <Navbar/>
        <div className="px-6 py-4">{children}</div>
      </body>
    </html>
  );
}
